on: 
    push:
        branches: [ master ]
    
    workflow_dispatch:
      inputs:
        target:
          description: 'Target IP Address or Domain to Scan'
          required: true
          default: ''
          type: string
        run_nmap:
          description: 'Execute Nmap Infrastructure Scan?'
          required: true
          type: boolean
          default: true
        run_whatweb:
          description: 'Execute WhatWeb Footprint Scan?'
          required: true
          type: boolean
          default: false
        run_nikto:
          description: 'Execute Nikto Vulnerability Scan?'
          required: true
          type: boolean
          default: false
        run_zap:
          description: 'Execute Zap Vulnerability Scan?'
          required: true
          type: boolean
          default: false

jobs:

    nmap:
        name: Nmap Scan Execution

        if: ${{ github.event_name == 'push' || inputs.run_nmap == true }}

        runs-on: ubuntu-latest

        steps:
    
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: install dependencies
              run: |
                python -m pip install --upgrade pip

                if [ -f requirements.txt ]; then
                    pip install -r requirements.txt
                fi
            
            - name: Check Syntax
              run: |
                python -m py_compile stock.py

            - name: Install tools
              run: |
                sudo apt-get update
                sudo apt-get install -y curl nmap xsltproc

            - name: Verify Flask app starts
              run: |
                python stock.py &
                sleep 10

            - name: Nmap Test
              env:
                EVENT_NAME: ${{ github.event_name }}
                FORM_TARGET: ${{ github.event.inputs.target }}
                DEFAULT_TARGET: '127.0.0.1'
              run: |
                if [ "$EVENT_NAME" = "workflow_dispatch" ] && [ -n "$FORM_TARGET" ]; then
                  TARGET="$FORM_TARGET"
                else
                  TARGET="$DEFAULT_TARGET"
                fi

                echo "🚀 Executing Nmap scan against target: $TARGET"
                nmap --script=vuln $TARGET -sV -oX nmap.xml
                xsltproc -o nmap.html /usr/share/nmap/nmap.xsl nmap.xml
                python nmap_parse.py
            
            - name: Upload Saved Output File
              uses: actions/upload-artifact@v4
              with:
                name: Artifacts-Nmap
                path: |
                  nmap_dashboard.html
                  nmap.xml

    whatweb:
        name: WhatWeb Scan Execution

        if: ${{ github.event_name == 'push' || inputs.run_whatweb== true }}

        runs-on: ubuntu-latest

        steps:
    
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: install dependencies
              run: |
                python -m pip install --upgrade pip

                if [ -f requirements.txt ]; then
                    pip install -r requirements.txt
                fi
            
            - name: Check Syntax
              run: |
                python -m py_compile stock.py

            - name: Install tools
              run: |
                sudo apt-get update
                sudo apt-get install -y curl whatweb

            - name: Verify Flask app starts
              run: |
                python stock.py &
                sleep 5
            
            - name: WhatWeb Test
              env:
                EVENT_NAME: ${{ github.event_name }}
                FORM_TARGET: ${{ github.event.inputs.target }}
                DEFAULT_TARGET: '127.0.0.1'
              run: |
                if [ "$EVENT_NAME" = "workflow_dispatch" ] && [ -n "$FORM_TARGET" ]; then
                  TARGET="$FORM_TARGET"
                else
                  TARGET="$DEFAULT_TARGET"
                fi

                echo "🚀 Executing whatweb scan against target: $TARGET"
                whatweb -v -a 3 --log-xml=whatweb.xml $TARGET
                python whatweb_parse.py
            
            - name: Upload Saved Output File
              uses: actions/upload-artifact@v4
              with:
                name: Artifacts-WhatWeb
                path: |
                  whatweb.xml
                  whatweb_dashboard.html

    nikto:
        name: Nikto Scan Execution

        if: ${{ github.event_name == 'push' || inputs.run_nikto == true }}

        runs-on: ubuntu-latest

        steps:
    
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: install dependencies
              run: |
                python -m pip install --upgrade pip

                if [ -f requirements.txt ]; then
                    pip install -r requirements.txt
                fi
            
            - name: Check Syntax
              run: |
                python -m py_compile stock.py

            - name: Install tools
              run: |
                sudo apt-get update
                sudo apt-get install -y curl nikto

            - name: Verify Flask app starts
              run: |
                python stock.py &
                sleep 5

            - name: Nikto Test
              env:
                EVENT_NAME: ${{ github.event_name }}
                FORM_TARGET: ${{ github.event.inputs.target }}
                DEFAULT_TARGET: '127.0.0.1'

              run: |
                if [ "$EVENT_NAME" = "workflow_dispatch" ] && [ -n "$FORM_TARGET" ]; then
                  TARGET="$FORM_TARGET"
                else
                  TARGET="$DEFAULT_TARGET"
                fi

                echo "🚀 Executing Nikto scan against target: $TARGET"
                nikto -host $TARGET -C all -o nikto.htm
                python nikto_parse.py nikto.htm nikto_dashboard.html
            
            - name: Upload Saved Output File
              uses: actions/upload-artifact@v4
              with:
                name: Artifacts-Nikto
                path: |
                  nikto.htm
                  nikto_dashboard.html

    zap_scan:
        name: Zap Scan Execution

        if: ${{ github.event_name == 'push' || inputs.run_zap == true }}

        runs-on: ubuntu-latest

        steps:
    
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: install dependencies
              run: |
                python -m pip install --upgrade pip

                if [ -f requirements.txt ]; then
                    pip install -r requirements.txt
                fi
            
            - name: Check Syntax
              run: |
                python -m py_compile stock.py

            - name: Install tools
              run: |
                sudo apt-get update
                sudo apt-get install -y curl nikto

            - name: Verify Flask app starts
              run: |
                python stock.py &
                sleep 10
            
            - name: ZAP Scan
              uses: zaproxy/action-baseline@v0.15.0
              with:
                docker_name: 'ghcr.io/zaproxy/zaproxy:bare'
                target: 'http://$TARGET:5000'
                rules_file_name: '.zap/rules.tsv'
                cmd_options: '-a'
            
            #- name: ZAP Scan
             # uses: zaproxy/action-baseline@v0.6.1
              #with:
               # docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
                #target: 'http://127.0.0.1:5000'
                #rules_file_name: '.zap/rules.tsv'
                #cmd_options: '-a'
            
            - name: Upload ZAP Report
              uses: actions/upload-artifact@v4
              with:
                name: zap-report
                path: |
                    report_html.html
                    report_json.json

    merge-artifacts:
        needs:
            - nmap
            - whatweb
            - nikto
        runs-on: ubuntu-latest
        steps:
          - name: Merge all parallel artifacts
            uses: actions/upload-artifact/merge@v4
            with:
                name: final-combined-artifact
                pattern: Artifacts-* 
                delete-merged: true
        
    verify-reports:
        name: Verify Scanners Output & Generate Dashboard
        needs: merge-artifacts # ⚠️ Must match your 4th job ID
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Download Merged Artifacts
            uses: actions/download-artifact@v4
            with:
                name: final-combined-artifact # ⚠️ Must match Job 4's upload name
                path: ./downloaded-artifact 

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.12'

          - name: Run Verification & Build HTML Report
            run: |
                python verify.py ./downloaded-artifact

        # This step saves your final status page back to GitHub Actions
          - name: Upload Security Summary Dashboard
            uses: actions/upload-artifact@v4
            if: always()
            with:
                name: execution-summary-report
                path: security-summary.html