name: WhatWeb Test

on: 
    push:
        branches: [ master ]
    
    pull_request:
        branches: [ master ]


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
    
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: install dependencies
              run: |
                python -m pip install --upgrade pip

                if [ -f requirements.txt ]; then
                    pip install -r requirements.txt
                fi
            
            - name: Check Syntax
              run: |
                python -m py_compile stock.py

            - name: Install tools
              run: |
                sudo apt-get update
                sudo apt-get install -y curl whatweb xsltproc

            - name: Verify Flask app starts
              run: |
                python stock.py &
                sleep 10
            
            - name: Check server
              run: |
                curl http://127.0.0.1:5000
            
            - name: WhatWeb Test
              run: |
                whatweb -v -a 3 --log-xml=whatweb.xml 127.0.0.1:5000
                xsltproc -o whatweb.html /usr/share/nmap/nmap.xsl whatweb.xml
            
            - name: Upload Saved Output File
              uses: actions/upload-artifact@v4
              with:
                name: deployment-logs
                path: 
                  whatweb.json
                  whatweb.html
            